### PR TITLE
Update CISCO-RTTMON-TC-MIB.my

### LINKED ISSUE #53: CSCwi58743 - Syntax issue in CISCO-RTTMON-TC-MIB.my
See #47

### PR DESCRIPTION
**Pull request by Hipska**
Typo fix

resolves #53

### CODE REVIEW

**Comment by kyzer-davis** [comment]
I don't have `smilint` handy. What error level and message does this produce?

**Comment by Hipska** [comment]
```
CISCO-RTTMON-TC-MIB.my:433: syntax error, unexpected UPPERCASE_IDENTIFIER, expecting SYNTAX
CISCO-RTTMON-TC-MIB.my:433: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:435: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:437: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:477: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:480: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:483: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:547: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:553: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:555: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:571: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:574: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:575: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:578: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:581: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:585: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:588: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:590: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:593: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:596: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:600: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:603: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:607: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:611: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:614: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:617: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:623: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:632: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:633: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:637: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:741: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:764: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:775: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:776: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:788: lexically unexpected character, skipping to end of line
CISCO-RTTMON-TC-MIB.my:977: lexically unexpected character, skipping to end of line
```

**Comment by kyzer-davis** [comment]
Totally missed that this is part of the existing issue #53 
I am working on a `CONTRIBUTING.md` file that details this but the gist is that the changes need to be done on the internal CIsco repo first then replicated out. 

This one is just removing a double-quote so it should not have taken the team this long. As such I have poked the devs behind the internal defect I filed CSCwi58743.

Also, the PR has to come from a Cisco Employee so I will need to close this; but I will link the issue when the PR comes across.

**Comment by Hipska** [comment]
What's the point of this repo then? It is so counter-intuitive to block all external contributions..

**Comment by kyzer-davis** [comment]
@Hipska, I understand the frustration. I would love to merge these typos type issues quickly and be done but if the source isn't updated we risk somebody else coming along with a different update that wipes a change like this out.

_External proposed PRs are fine_, I just have to file an Cisco Defect to ensure the changes are picked up internally then replicated back out by the developer that owns the source files. 

---

Some further context:

Historically, this repo replaced the public/anonymous `ftp.cisco.com` location where the MIBs files were located before before that location was deprecated. MIB files changes/updates have always been replicated from internal to external with the contents of the MIB files being updated by only Cisco Developers.

GitHub was selected as the new location because it continues public access without the requirement of logging into a Cisco.com site. Plus it has nice new features like commit history and rendering of the support list html files via GitHub pages.

**Comment by Hipska** [comment]
Another nice feature is an easy way for external contributors to contribute fixes 😉

**Pull request closed without merging**
